# Generated by Django 5.0.3 on 2024-03-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_type', models.CharField(choices=[('education', 'Education')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('date_range', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='profiles/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoryApp.album')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoryApp.person')),
            ],
        ),
    ]
