# Generated by Django 5.0.3 on 2024-03-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Personal Photo', 'verbose_name_plural': 'Personal Photos'},
        ),
        migrations.CreateModel(
            name='GroupPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='group_photos/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoryApp.album')),
            ],
            options={
                'verbose_name': 'Public Photo',
                'verbose_name_plural': 'Public Photos',
            },
        ),
    ]
