# Generated by Django 5.0.3 on 2024-03-27 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoryApp', '0002_alter_photo_options_groupphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='joint_photos/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoryApp.album')),
                ('people', models.ManyToManyField(related_name='joint_photos', to='fotoryApp.person')),
            ],
        ),
    ]
